[build]
  command = "pip install -r requirements.txt && python freeze.py"
  publish = "docs"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404