# Test url_for output
import sys
sys.path.insert(0, '.')

from app import app, get_all_tags
from flask import url_for

with app.test_request_context():
    tags = get_all_tags()
    print("First 10 tag URLs generated by url_for:")
    for tag in tags[:10]:
        url = url_for('tag_posts', tag=tag, _external=True)
        print(f"  '{tag}' -> {url}")
