param(
  [Parameter(Mandatory=$true)]
  [string]$PostPath,                      # e.g. .\posts\2025-09-08-my-post.md
  [string]$Message = "Publish blog post"  # optional commit message
)

function Normalize-Post([string]$fp){
  if(-not (Test-Path $fp)){ throw "Post not found: $fp" }

  $raw = Get-Content -Raw $fp -Encoding UTF8

  # 1) re-decode mojibake
  $bytes1252 = [Text.Encoding]::GetEncoding(1252).GetBytes($raw)
  $txt = [Text.Encoding]::UTF8.GetString($bytes1252)

  # 2) normalize punctuation
  $map = @{
    ([char]0x2018)="'"; ([char]0x2019)="'"; ([char]0x2032)="'";
    ([char]0x201C)='"'; ([char]0x201D)='"'; ([char]0x2033)='"';
    ([char]0x2013)='-';  ([char]0x2014)='--'; ([char]0x00A0)=' ';
    ([char]0xFEFF)=''
  }
  foreach($k in $map.Keys){ $txt = $txt -replace [regex]::Escape([string]$k), [string]$map[$k] }

  # 3) normalize “Download the Matrix” header if present
  $txt = $txt -replace "##\s*.*Download.*Matrix.*","## Download the Matrix"

  # 4) ensure UTF-8 (no BOM)
  Set-Content $fp $txt -Encoding UTF8
}

function Get-Slug([string]$fp){
  $content = Get-Content -Raw $fp -Encoding UTF8
  # very simple slug extractor from front matter
  if($content -match "(?ms)^---\s*.*?^slug:\s*([^\r\n]+)\s*.*?^---"){
    return ($matches[1].Trim())
  }
  # fallback: filename without extension
  return [IO.Path]::GetFileNameWithoutExtension($fp)
}

# --- run ---
Normalize-Post $PostPath
$slug = Get-Slug $PostPath
Write-Host "✓ Post normalized. Slug: $slug"

# Freeze and publish
python .\freeze.py

$dest = ".\docs\blog\$slug\index.html"
if(-not (Test-Path $dest)){ throw "Freeze did not emit $dest. Check front matter (slug/date)." }

# ensure CNAME regenerated by freeze.py or write it here if you prefer:
# Set-Content .\docs\CNAME 'azure-noob.com'

git add $PostPath
git add -f .\docs\
git commit -m ("{0}: {1}" -f $Message, $slug)
git push origin main

Write-Host "✓ Published: https://azure-noob.com/blog/$slug/"
