name: Build and Deploy (GitHub Pages)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write   # required by peaceiris/actions-gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build static site
        env:
          SITE_URL: https://azure-noob.com
        run: python freeze.py

      # Optional: ensure CNAME is present if freeze.py didn't write it
      - name: Add CNAME
        run: |
          echo "azure-noob.com" > build/CNAME
          echo "www.azure-noob.com" >> build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          enable_jekyll: false
          force_orphan: true
