name: Build & Deploy Site

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install powershell-yaml

      - name: Validate content
        shell: pwsh
        run: ./tools/validate-content.ps1 -RepoRoot $PWD

      - name: Freeze static site into docs/
        run: python freeze.py

      - name: Upload artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs/

      # Publish docs/ to gh-pages branch (GitHub Pages)
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
